/**
 * WorkflowModel — version-3 WorkflowSnapshot types and command dispatch.
 *
 * This module defines the authoritative domain model for workflow execution.
 * All state changes happen through validated command dispatch producing a new
 * snapshot revision. No direct mutation escapes this boundary.
 *
 * Ids are opaque tokens generated by the module, unique within their record map.
 * They never encode parentage or a workflow type.
 */

import { z } from 'zod';

// ─── Primitive helpers ────────────────────────────────────────────────────────

export type Id = string;
let idCounter = 0;

/** Generate an opaque, monotonically increasing Id. */
export function genId(): Id {
  return `id-${Date.now().toString(36)}-${(++idCounter).toString(36)}`;
}

export function resetIdCounter(): void {
  idCounter = 0;
}

// ─── Zod schemas for the version-3 model ─────────────────────────────────────

export const JsonValueSchema: z.ZodType<JsonValue> = z.lazy(() =>
  z.union([
    z.null(),
    z.boolean(),
    z.number(),
    z.string(),
    z.array(JsonValueSchema),
    z.record(JsonValueSchema),
  ])
);
export type JsonValue =
  null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export const VersionRefSchema = z.object({ id: z.string(), version: z.string() });
export type VersionRef = z.infer<typeof VersionRefSchema>;

export const ExecutionRefSchema = z.object({
  scopeId: z.string(),
  executionId: z.string(),
  attemptId: z.string(),
});
export type ExecutionRef = z.infer<typeof ExecutionRefSchema>;

// ─── Run ─────────────────────────────────────────────────────────────────────

export const WorkflowRunSchema = z.object({
  id: z.string(),
  revision: z.number().int().min(1),
  title: z.string(),
  definitionDigest: z.string(),
  rootScopeId: z.string(),
  input: z.record(JsonValueSchema),
  status: z.enum(['active', 'succeeded', 'failed', 'cancelled']),
  createdAt: z.string(),
  updatedAt: z.string(),
});
export type WorkflowRun = z.infer<typeof WorkflowRunSchema>;

// ─── Scope ────────────────────────────────────────────────────────────────────

export const ExecutionScopeSchema = z.object({
  id: z.string(),
  flowId: z.string(),
  parentExecutionId: z.string().nullable(),
  branchKey: z.string().nullable(),
  workItem: VersionRefSchema.nullable(),
  collection: VersionRefSchema.nullable(),
  input: z.record(JsonValueSchema),
  cursorExecutionId: z.string(),
  status: z.enum(['active', 'succeeded', 'failed', 'cancelled']),
  terminalResultId: z.string().nullable(),
});
export type ExecutionScope = z.infer<typeof ExecutionScopeSchema>;

// ─── Step Execution ───────────────────────────────────────────────────────────

export const StepExecutionSchema = z.object({
  id: z.string(),
  scopeId: z.string(),
  nodeId: z.string(),
  occurrence: z.number().int().min(1),
  predecessorExecutionId: z.string().nullable(),
  currentAttemptId: z.string(),
  childScopeIds: z.array(z.string()),
  status: z.enum(['ready', 'active', 'waiting', 'finished', 'cancelled']),
});
export type StepExecution = z.infer<typeof StepExecutionSchema>;

// ─── Attempt ──────────────────────────────────────────────────────────────────

export const AttemptSchema = z.object({
  id: z.string(),
  executionId: z.string(),
  attemptNumber: z.number().int().min(1),
  status: z.enum([
    'ready',
    'running',
    'waiting',
    'completed',
    'interrupted',
    'unknown',
    'cancelled',
  ]),
  input: z.record(JsonValueSchema),
  consumedResultIds: z.array(z.string()),
  subjects: z.array(VersionRefSchema),
  allowedArtifactIds: z.array(z.string()),
  baselineSnapshotId: z.string().nullable(),
  resultId: z.string().nullable(),
  createdAt: z.string(),
  finishedAt: z.string().nullable(),
});
export type Attempt = z.infer<typeof AttemptSchema>;

// ─── Result ───────────────────────────────────────────────────────────────────

export const CheckReportSchema = z.object({
  checkId: z.string(),
  outcome: z.string(),
  subjects: z.array(VersionRefSchema),
  evidence: z.array(VersionRefSchema),
});
export type CheckReport = z.infer<typeof CheckReportSchema>;

export const ResultRecordSchema = z.object({
  id: z.string(),
  version: z.string(),
  execution: ExecutionRefSchema,
  outcome: z.string(),
  summary: z.string(),
  outputs: z.record(JsonValueSchema),
  subjects: z.array(VersionRefSchema),
  evidence: z.array(VersionRefSchema),
  checks: z.array(CheckReportSchema),
  authority: z.enum(['assertion', 'verification', 'human', 'policy', 'engine']),
  producerId: z.string(),
  recordedRevision: z.number().int(),
});
export type ResultRecord = z.infer<typeof ResultRecordSchema>;

// ─── Decision ─────────────────────────────────────────────────────────────────

export const DecisionPolicySchema = z.object({
  authority: z.enum(['human', 'policy']),
  allowedActors: z.array(z.string()),
  outcomes: z.array(z.string()),
  onInvalidated: z.string(),
  onExpired: z.string(),
});
export type DecisionPolicy = z.infer<typeof DecisionPolicySchema>;

export const DecisionResolutionSchema = z.object({
  outcome: z.string(),
  parameters: z.record(JsonValueSchema),
  resolverId: z.string(),
  authority: z.enum(['human', 'policy']),
  revision: z.number().int(),
});
export type DecisionResolution = z.infer<typeof DecisionResolutionSchema>;

export const DecisionRequestSchema = z.object({
  id: z.string(),
  owner: ExecutionRefSchema,
  purpose: z.enum(['step', 'retry']),
  subjects: z.array(VersionRefSchema),
  policy: DecisionPolicySchema,
  status: z.enum(['pending', 'resolved', 'invalidated', 'expired', 'revoked']),
  resolution: DecisionResolutionSchema.nullable(),
});
export type DecisionRequest = z.infer<typeof DecisionRequestSchema>;

// ─── Supporting records ───────────────────────────────────────────────────────

export const RetryBudgetSchema = z.object({
  id: z.string(),
  policyId: z.string(),
  owner: z.discriminatedUnion('kind', [
    z.object({ kind: z.literal('occurrence'), id: z.string() }),
    z.object({ kind: z.literal('scope'), id: z.string() }),
  ]),
  chargedAttemptIds: z.array(z.string()),
  maximumAttempts: z.number().int().min(1),
});
export type RetryBudget = z.infer<typeof RetryBudgetSchema>;

export const ResourceClaimSchema = z.object({
  id: z.string(),
  execution: ExecutionRefSchema,
  resourceKey: z.string(),
  mode: z.enum(['shared', 'exclusive']),
  status: z.enum(['held', 'quarantined', 'released']),
});
export type ResourceClaim = z.infer<typeof ResourceClaimSchema>;

export const ValidationRecordSchema = z.object({
  id: z.string(),
  execution: ExecutionRefSchema.nullable(),
  code: z.string(),
  message: z.string(),
  sourcePath: z.string().nullable(),
  recordedRevision: z.number().int(),
});
export type ValidationRecord = z.infer<typeof ValidationRecordSchema>;

export const TransitionRecordSchema = z.object({
  id: z.string(),
  scopeId: z.string(),
  transitionId: z.string(),
  fromExecutionId: z.string(),
  toExecutionId: z.string(),
  consumedResultId: z.string(),
  recordedRevision: z.number().int(),
});
export type TransitionRecord = z.infer<typeof TransitionRecordSchema>;

// ─── Host correlation ─────────────────────────────────────────────────────────

export const HostSessionLinkSchema = z.object({
  id: z.string(),
  hostId: z.string(),
  nativeSessionId: z.string(),
  parentLinkId: z.string().nullable(),
});
export type HostSessionLink = z.infer<typeof HostSessionLinkSchema>;

export const HostBindingSchema = z.object({
  id: z.string(),
  sessionLinkId: z.string(),
  nativeCallId: z.string(),
  actorId: z.string(),
  execution: ExecutionRefSchema,
  role: z.enum(['primary', 'nested']),
  status: z.enum(['admitted', 'completed', 'unknown', 'cancelled']),
});
export type HostBinding = z.infer<typeof HostBindingSchema>;

// ─── Command tracking ─────────────────────────────────────────────────────────

export const AppliedCommandSchema = z.object({
  id: z.string(),
  fingerprint: z.string(),
  appliedRevision: z.number().int(),
  createdIds: z.array(z.string()),
});
export type AppliedCommand = z.infer<typeof AppliedCommandSchema>;

// ─── WorkflowSnapshot (version 3) ─────────────────────────────────────────────

export const WorkflowSnapshotSchema = z.object({
  formatVersion: z.literal(3),
  run: WorkflowRunSchema,
  scopes: z.record(z.string(), ExecutionScopeSchema),
  executions: z.record(z.string(), StepExecutionSchema),
  attempts: z.record(z.string(), AttemptSchema),
  results: z.record(z.string(), ResultRecordSchema),
  decisions: z.record(z.string(), DecisionRequestSchema),
  retryBudgets: z.record(z.string(), RetryBudgetSchema),
  resourceClaims: z.record(z.string(), ResourceClaimSchema),
  validations: z.record(z.string(), ValidationRecordSchema),
  transitions: z.record(z.string(), TransitionRecordSchema),
  appliedCommands: z.record(z.string(), AppliedCommandSchema),
  host: z.object({
    sessions: z.record(z.string(), HostSessionLinkSchema),
    bindings: z.record(z.string(), HostBindingSchema),
  }),
});
export type WorkflowSnapshot = z.infer<typeof WorkflowSnapshotSchema>;

// ─── Commands ─────────────────────────────────────────────────────────────────

export type Command =
  | { kind: 'create'; definitionDigest: string; title: string; input: Record<string, JsonValue> }
  | {
      kind: 'complete';
      execution: ExecutionRef;
      bindingId: string;
      outcome: string;
      summary: string;
      outputs: Record<string, JsonValue>;
    }
  | { kind: 'resolveDecision'; decisionId: string; outcome: string; approvedMaximum?: number }
  | { kind: 'cancelScope'; scopeId: string };

// ─── Command dispatch ─────────────────────────────────────────────────────────

export interface CommandOutput {
  snapshot: WorkflowSnapshot;
  validations: ValidationRecord[];
}

let validationSeq = 0;

function val(
  code: string,
  message: string,
  execution: ExecutionRef | null = null,
  sourcePath: string | null = null
): ValidationRecord {
  return {
    id: genId(),
    execution,
    code,
    message,
    sourcePath,
    recordedRevision: -1, // filled in by dispatch
  };
}

/**
 * Validate and apply a command to the given snapshot, returning the new snapshot
 * and any validation records. Returns null snapshot + validations on rejection.
 */
export function dispatchCommand(
  snapshot: WorkflowSnapshot | null,
  command: Command,
  commandId: string,
  now: string
): CommandOutput {
  const validations: ValidationRecord[] = [];

  switch (command.kind) {
    case 'create':
      return handleCreate(snapshot, command, commandId, validations, now);
    case 'complete':
      return handleComplete(snapshot, command, commandId, validations, now);
    case 'resolveDecision':
      return handleResolveDecision(snapshot, command, commandId, validations, now);
    case 'cancelScope':
      return handleCancelScope(snapshot, command, commandId, validations, now);
    default:
      validations.push(
        val('UNKNOWN_COMMAND', `Unknown command kind: ${(command as Command).kind}`)
      );
      return { snapshot: snapshot!, validations };
  }
}

function handleCreate(
  _snapshot: WorkflowSnapshot | null,
  command: Command & { kind: 'create' },
  commandId: string,
  validations: ValidationRecord[],
  now: string
): CommandOutput {
  const runId = genId();
  const rootScopeId = genId();
  const rootExecId = genId();
  const rootAttemptId = genId();

  const snapshot: WorkflowSnapshot = {
    formatVersion: 3,
    run: {
      id: runId,
      revision: 1,
      title: command.title,
      definitionDigest: command.definitionDigest,
      rootScopeId,
      input: command.input,
      status: 'active',
      createdAt: now,
      updatedAt: now,
    },
    scopes: {
      [rootScopeId]: {
        id: rootScopeId,
        flowId: '',
        parentExecutionId: null,
        branchKey: null,
        workItem: null,
        collection: null,
        input: command.input,
        cursorExecutionId: rootExecId,
        status: 'active',
        terminalResultId: null,
      },
    },
    executions: {
      [rootExecId]: {
        id: rootExecId,
        scopeId: rootScopeId,
        nodeId: '', // resolved from definition
        occurrence: 1,
        predecessorExecutionId: null,
        currentAttemptId: rootAttemptId,
        childScopeIds: [],
        status: 'ready',
      },
    },
    attempts: {
      [rootAttemptId]: {
        id: rootAttemptId,
        executionId: rootExecId,
        attemptNumber: 1,
        status: 'ready',
        input: command.input,
        consumedResultIds: [],
        subjects: [],
        allowedArtifactIds: [],
        baselineSnapshotId: null,
        resultId: null,
        createdAt: now,
        finishedAt: null,
      },
    },
    results: {},
    decisions: {},
    retryBudgets: {},
    resourceClaims: {},
    validations: {},
    transitions: {},
    appliedCommands: {
      [genId()]: {
        id: genId(),
        fingerprint: commandId,
        appliedRevision: 1,
        createdIds: [runId, rootScopeId, rootExecId, rootAttemptId],
      },
    },
    host: { sessions: {}, bindings: {} },
  };

  return { snapshot, validations };
}

function handleComplete(
  snapshot: WorkflowSnapshot,
  command: Command & { kind: 'complete' },
  commandId: string,
  validations: ValidationRecord[],
  now: string
): CommandOutput {
  const { execution, outcome, summary, outputs } = command;

  // Validate execution exists
  const exec = snapshot.executions[execution.executionId];
  if (!exec) {
    validations.push(
      val('UNKNOWN_EXECUTION', `Execution ${execution.executionId} not found`, execution)
    );
    return { snapshot, validations };
  }

  // Validate attempt exists and is running
  const attempt = snapshot.attempts[execution.attemptId];
  if (!attempt) {
    validations.push(val('UNKNOWN_ATTEMPT', `Attempt ${execution.attemptId} not found`, execution));
    return { snapshot, validations };
  }
  if (attempt.status !== 'running') {
    validations.push(
      val(
        'INVALID_ATTEMPT_STATUS',
        `Attempt ${execution.attemptId} is ${attempt.status}, expected running`,
        execution
      )
    );
    return { snapshot, validations };
  }

  const newRev = snapshot.run.revision + 1;
  const resultId = genId();
  const resultRecord = {
    id: resultId,
    version: `${newRev}`,
    execution,
    outcome,
    summary,
    outputs,
    subjects: [],
    evidence: [],
    checks: [],
    authority: 'assertion' as const,
    producerId: command.bindingId,
    recordedRevision: newRev,
  };

  // Update attempt
  const updatedAttempt = { ...attempt, status: 'completed' as const, resultId, finishedAt: now };
  const updatedExec = { ...exec, status: 'finished' as const };

  const newSnapshot: WorkflowSnapshot = {
    ...snapshot,
    run: { ...snapshot.run, revision: newRev, updatedAt: now },
    executions: { ...snapshot.executions, [execution.executionId]: updatedExec },
    attempts: { ...snapshot.attempts, [execution.attemptId]: updatedAttempt },
    results: { ...snapshot.results, [resultId]: resultRecord },
    appliedCommands: {
      ...snapshot.appliedCommands,
      [genId()]: {
        id: genId(),
        fingerprint: commandId,
        appliedRevision: newRev,
        createdIds: [resultId],
      },
    },
  };

  return { snapshot: newSnapshot, validations };
}

function handleResolveDecision(
  snapshot: WorkflowSnapshot,
  command: Command & { kind: 'resolveDecision' },
  commandId: string,
  validations: ValidationRecord[],
  now: string
): CommandOutput {
  const decision = snapshot.decisions[command.decisionId];
  if (!decision) {
    validations.push(val('UNKNOWN_DECISION', `Decision ${command.decisionId} not found`));
    return { snapshot, validations };
  }
  if (decision.status !== 'pending') {
    validations.push(
      val(
        'DECISION_NOT_PENDING',
        `Decision ${command.decisionId} status is ${decision.status}, expected pending`
      )
    );
    return { snapshot, validations };
  }

  const newRev = snapshot.run.revision + 1;
  const updatedDecision = {
    ...decision,
    status: 'resolved' as const,
    resolution: {
      outcome: command.outcome,
      parameters: {},
      resolverId: 'command',
      authority: 'policy' as const,
      revision: newRev,
    },
  };

  const newSnapshot: WorkflowSnapshot = {
    ...snapshot,
    run: { ...snapshot.run, revision: newRev, updatedAt: now },
    decisions: { ...snapshot.decisions, [command.decisionId]: updatedDecision },
    appliedCommands: {
      ...snapshot.appliedCommands,
      [genId()]: { id: genId(), fingerprint: commandId, appliedRevision: newRev, createdIds: [] },
    },
  };

  return { snapshot: newSnapshot, validations };
}

function handleCancelScope(
  snapshot: WorkflowSnapshot,
  command: Command & { kind: 'cancelScope' },
  commandId: string,
  validations: ValidationRecord[],
  now: string
): CommandOutput {
  const scope = snapshot.scopes[command.scopeId];
  if (!scope) {
    validations.push(val('UNKNOWN_SCOPE', `Scope ${command.scopeId} not found`));
    return { snapshot, validations };
  }
  if (scope.status !== 'active') {
    validations.push(
      val('SCOPE_NOT_ACTIVE', `Scope ${command.scopeId} status is ${scope.status}, expected active`)
    );
    return { snapshot, validations };
  }

  const newRev = snapshot.run.revision + 1;
  const updatedScope = { ...scope, status: 'cancelled' as const };

  const newSnapshot: WorkflowSnapshot = {
    ...snapshot,
    run: { ...snapshot.run, revision: newRev, updatedAt: now },
    scopes: { ...snapshot.scopes, [command.scopeId]: updatedScope },
    appliedCommands: {
      ...snapshot.appliedCommands,
      [genId()]: { id: genId(), fingerprint: commandId, appliedRevision: newRev, createdIds: [] },
    },
  };

  return { snapshot: newSnapshot, validations };
}

/**
 * Detect duplicate command (same fingerprint at same or later revision).
 */
export function isDuplicate(snapshot: WorkflowSnapshot, fingerprint: string): boolean {
  return Object.values(snapshot.appliedCommands).some((c) => c.fingerprint === fingerprint);
}
