#!/usr/bin/env bash
#MISE description="Type check TypeScript files without emitting"
#MISE sources=["src/**/*.ts", "src/**/*.tsx", "test/**/*.ts", "scripts/**/*.ts", "smoke/**/*.ts", "tsconfig.json"]

tsc --noEmit
