import { readdir, readFile, unlink, mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { profilesDir, harnessDir } from './paths.ts';

const MANAGED_MARKER_PREFIX = '# MANAGED BY session-guard';
const MANAGED_MARKER_SUFFIX = 'do not edit';

const MANAGED_MARKER_LINE = `${MANAGED_MARKER_PREFIX} — ${MANAGED_MARKER_SUFFIX}`;

/** First line of the ignore file this plugin owns — how it recognises its own. */
const IGNORE_HEADER = '# Generated by session-guard from profiles/<id>/agents. Do not commit.';

/** The marker line of `content`, wherever ownership is recorded, or `null`. */
function markerLineOf(content: string): string | null {
  const firstLine = content.split('\n', 1)[0];
  if (firstLine.startsWith(MANAGED_MARKER_PREFIX)) return firstLine.trimEnd();

  if (firstLine.trim() === '---') {
    const endFm = content.indexOf('\n---\n', 1);
    if (endFm !== -1) {
      const lineAfterFm = content
        .slice(endFm + 5)
        .split('\n', 1)[0]
        .trimEnd();
      if (lineAfterFm.startsWith(MANAGED_MARKER_PREFIX)) return lineAfterFm;
    }
  }

  return null;
}

/**
 * Check whether `content` is owned by this plugin.
 *
 * Ownership is recognised at two locations:
 *   1. After YAML frontmatter (i.e. the first non-frontmatter line).
 *   2. The very first line of the file (legacy — pre-frontmatter awareness).
 */
function isOwned(content: string): boolean {
  return markerLineOf(content) !== null;
}

/**
 * Read a target file's bytes, returning `null` if the file does not exist.
 */
async function tryReadFile(p: string): Promise<string | null> {
  try {
    return await readFile(p, 'utf-8');
  } catch {
    return null;
  }
}

function injectManagedMarker(content: string): string {
  const marker = MANAGED_MARKER_LINE;
  const firstLine = content.split('\n', 1)[0];
  if (firstLine.trim() === '---') {
    const endFm = content.indexOf('\n---\n', 1);
    if (endFm !== -1) {
      const beforeBody = content.slice(0, endFm + 5);
      const body = content.slice(endFm + 5);
      return beforeBody + marker + '\n' + body;
    }
  }
  return marker + '\n' + content;
}

/**
 * The agents a profile ships.
 *
 * `profile.json`'s `agents` is the source of truth when the profile declares
 * one. When it does not, the default is what the agents directory holds — the
 * profile ships what it ships, and there is no second list to keep in step.
 *
 * Only the profile's own declaration counts here, never an inherited one:
 * these names have to match files under this profile's own directory, and an
 * ancestor's roster describes the ancestor's.
 *
 * Names come back bare (`code`); `qualifyAgentName` makes them `android_code`.
 */
export async function listProfileAgents(
  profileId: string,
  profilesDirectory: string
): Promise<string[]> {
  let agentsSubdir = 'agents';
  let declared: string[] | undefined;
  try {
    const meta = JSON.parse(
      await readFile(path.join(profilesDirectory, profileId, 'profile.json'), 'utf-8')
    ) as { agentsDir?: string; agents?: string[] };
    agentsSubdir = meta.agentsDir ?? 'agents';
    if (Array.isArray(meta.agents)) declared = meta.agents;
  } catch {
    // No profile.json, or unreadable: the default subdirectory is still worth a look.
  }
  // A declared roster keeps the order its author wrote; only the directory
  // listing is sorted, because a directory has no order of its own.
  if (declared !== undefined) return [...new Set(declared)];

  try {
    const entries = await readdir(path.join(profilesDirectory, profileId, agentsSubdir), {
      withFileTypes: true,
    });
    return entries
      .filter((entry) => entry.isFile() && entry.name.endsWith('.md'))
      .map((entry) => entry.name.slice(0, -'.md'.length))
      .sort();
  } catch {
    return [];
  }
}

export async function syncProfileAgents(
  profileId: string,
  projectDir: string,
  log?: (msg: string) => void
): Promise<void> {
  const logMsg = log ?? (() => {});

  const pDir = profilesDir(projectDir);
  const hDir = harnessDir(projectDir);
  const opencodeAgentsDir = path.join(hDir, 'agents');

  // Load profile metadata to find agentsDir
  const profileJsonPath = path.join(pDir, profileId, 'profile.json');
  if (!existsSync(profileJsonPath)) {
    logMsg(`[profile-agent-sync] No profile.json for "${profileId}" at ${profileJsonPath}`);
    return;
  }

  let profileMeta: { agentsDir?: string };
  try {
    profileMeta = JSON.parse(await readFile(profileJsonPath, 'utf-8'));
  } catch (err) {
    logMsg(
      `[profile-agent-sync] Failed to parse ${profileJsonPath}: ${err instanceof Error ? err.message : String(err)}`
    );
    return;
  }

  const sourceAgentsDir = path.join(pDir, profileId, profileMeta.agentsDir ?? 'agents');
  // Flat: `.opencode/agents/<profileId>_<name>.md`, not one directory per
  // profile. The host derives an agent's name from the path under its agents
  // directory, so this registers as `<profileId>_<name>` — which is what
  // `qualifyAgentName` produces, and what a stage's `allowedAgents` is
  // compared against.
  //
  // The profile lives in the file name because the directory no longer keeps
  // profiles apart: `base` and `android` both ship `code.md`, and in a flat
  // directory under their bare names one would silently overwrite the other.
  const targetAgentsDir = opencodeAgentsDir;
  const targetNameOf = (sourceFile: string): string => `${profileId}_${sourceFile}`;

  // Collect source files (*.md only), keeping to the profile's roster: a
  // declared `agents` list is the source of truth, and what it leaves out is
  // not this profile's to register.
  const roster = new Set(await listProfileAgents(profileId, pDir));
  let sourceFiles: string[];
  if (!existsSync(sourceAgentsDir)) {
    logMsg(`[profile-agent-sync] Source agents dir does not exist: ${sourceAgentsDir}`);
    sourceFiles = [];
  } else {
    try {
      const entries = await readdir(sourceAgentsDir, { withFileTypes: true });
      sourceFiles = entries
        .filter((entry) => entry.isFile() && entry.name.endsWith('.md'))
        .map((entry) => entry.name)
        .filter((name) => {
          if (roster.has(name.slice(0, -'.md'.length))) return true;
          logMsg(`[profile-agent-sync] "${name}" is not on ${profileId}'s agents list; skipped`);
          return false;
        });
    } catch (err) {
      logMsg(
        `[profile-agent-sync] Error reading ${sourceAgentsDir}: ${err instanceof Error ? err.message : String(err)}`
      );
      return;
    }
  }

  // This profile's files in the flat directory, by their `<profileId>_` prefix.
  //
  // The sweep must not reach past them: the same directory holds other
  // profiles' agents and whatever the user keeps there, and a profile that
  // swept those away would break sessions it knows nothing about. The prefix
  // is what draws that line, and the ownership marker is checked on top of it.
  const targetPrefix = `${profileId}_`;
  let existingTargetFiles: string[];
  try {
    const entries = await readdir(targetAgentsDir, { withFileTypes: true });
    existingTargetFiles = entries
      .filter(
        (entry) =>
          entry.isFile() && entry.name.endsWith('.md') && entry.name.startsWith(targetPrefix)
      )
      .map((entry) => entry.name);
  } catch {
    existingTargetFiles = [];
  }

  const expectedTargets = new Set(sourceFiles.map(targetNameOf));
  const staleFiles = existingTargetFiles.filter((name) => !expectedTargets.has(name));
  for (const stale of staleFiles) {
    const targetPath = path.join(targetAgentsDir, stale);
    const targetContent = await tryReadFile(targetPath);
    if (targetContent === null) continue;

    if (!isOwned(targetContent)) {
      logMsg(
        `[profile-agent-sync] COLLISION: unowned file "${stale}" at ${targetPath} would be stale — preserved unchanged`
      );
      continue;
    }

    try {
      await unlink(targetPath);
      logMsg(`[profile-agent-sync] Removed stale agent: ${stale}`);
    } catch (err) {
      logMsg(
        `[profile-agent-sync] Error removing stale agent ${stale}: ${err instanceof Error ? err.message : String(err)}`
      );
    }
  }

  // Copy source files to target with managed marker
  for (const sourceFile of sourceFiles) {
    const sourcePath = path.join(sourceAgentsDir, sourceFile);
    const targetPath = path.join(targetAgentsDir, targetNameOf(sourceFile));

    try {
      let content: string;
      try {
        content = await readFile(sourcePath, 'utf-8');
      } catch (err) {
        logMsg(
          `[profile-agent-sync] Error reading ${sourcePath}: ${err instanceof Error ? err.message : String(err)}`
        );
        continue;
      }

      // If target exists and is not owned, preserve it with a diagnostic
      const existingTarget = await tryReadFile(targetPath);
      if (existingTarget !== null && !isOwned(existingTarget)) {
        logMsg(
          `[profile-agent-sync] COLLISION: unowned file "${sourceFile}" at ${targetPath} preserved unchanged`
        );
        continue;
      }

      const prefixed = isOwned(content) ? content : injectManagedMarker(content);

      await mkdir(path.dirname(targetPath), { recursive: true });
      await writeFile(targetPath, prefixed, 'utf-8');
      logMsg(`[profile-agent-sync] Synced agent: ${targetNameOf(sourceFile)}`);
    } catch (err) {
      logMsg(
        `[profile-agent-sync] Error copying ${sourceFile}: ${err instanceof Error ? err.message : String(err)}`
      );
    }
  }

  await markGenerated(targetAgentsDir, logMsg);
}

/**
 * Keep git from seeing the synced copies, without hiding anybody else's files.
 *
 * These files are copies of `profiles/<id>/agents/*.md`, which is what is
 * actually committed — they are derived, and they carry an ownership marker
 * saying so. Left untracked they are swept up by `commit-task.ts`, which
 * stages everything when it is given no paths, and the commit then carries
 * files no task ever touched. The delivery permit expected none of them, so
 * the receipt was refused and the workflow stopped in `commit` — with the
 * agent seeing only 'nothing staged to commit' from the retry that followed.
 *
 * The directory is flat and shared, so the ignore file names the managed files
 * one by one instead of ignoring everything in it. A blanket `*` here would
 * hide the agents a user keeps in the same directory, and those are theirs to
 * commit or not.
 *
 * The list is rebuilt from what is actually on disk, across every profile —
 * syncing one profile must not drop another profile's files off it.
 *
 * A `.gitignore` this plugin did not write is left exactly as it is: the
 * directory is shared, and an ignore file in it may be the user's own.
 */
async function markGenerated(
  targetAgentsDir: string,
  logMsg: (msg: string) => void
): Promise<void> {
  const ignorePath = path.join(targetAgentsDir, '.gitignore');
  try {
    await mkdir(targetAgentsDir, { recursive: true });

    let entries;
    try {
      entries = await readdir(targetAgentsDir, { withFileTypes: true });
    } catch {
      return;
    }

    const managed: string[] = [];
    for (const entry of entries) {
      if (!entry.isFile() || !entry.name.endsWith('.md')) continue;
      const content = await tryReadFile(path.join(targetAgentsDir, entry.name));
      if (content !== null && isOwned(content)) managed.push(entry.name);
    }
    managed.sort();

    const body =
      IGNORE_HEADER +
      '\n# Only the files listed here are managed; anything else in this\n' +
      '# directory belongs to you.\n' +
      '/.gitignore\n' +
      managed.map((name) => `/${name}\n`).join('');

    const existing = await tryReadFile(ignorePath);
    if (existing === body) return;
    if (existing !== null && !existing.startsWith(IGNORE_HEADER)) {
      logMsg(`[profile-agent-sync] ${ignorePath} was not written by this plugin — left unchanged`);
      return;
    }
    await writeFile(ignorePath, body, 'utf-8');
    logMsg(
      `[profile-agent-sync] Listed ${managed.length} generated agent file(s) in ${ignorePath}`
    );
  } catch (err) {
    logMsg(
      `[profile-agent-sync] Could not mark ${targetAgentsDir} as generated: ${err instanceof Error ? err.message : String(err)}`
    );
  }
}
