name: Publish to GitHub Packages

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile

      - run: mise run build

      - run: |
          cat <<-EOF > .npmrc
          //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
          @eanekrasov:registry=https://npm.pkg.github.com
          EOF

      - run: npm publish
